language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
script:
  - yarn test --coverage
  - yarn build
  - "echo  \"Linting commit message(s). You can find the rules here: https://github.com/marionebl/commitlint/tree/master/@commitlint/config-angular#rules\""
  - ./node_modules/.bin/commitlint-travis
